name: Build & Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build and Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: "18.15.0"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.2
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE }}
          FIREBASE_PROJECT: amaurychalot-portfolio
